import type { ThemeOptions } from '@rneui/themed'
import { StyleSheet } from 'react-native'
import { TYPOGRAPHY } from '../constants'

export const purchasingStyles = (theme: ThemeOptions) => StyleSheet.create({
    // ===== PURCHASE =====
    quantityStepperHint: {
        marginTop: -8,
        paddingHorizontal: 10,
        fontSize: 12,
        color: theme.colors.grey2,
    },
    purchaseSummaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 10,
    },
    purchaseSummaryLabel: {
        fontWeight: '600',
        color: theme.colors.tertiary,
        fontSize: 14,
    },
    purchaseSummaryValue: {
        fontWeight: '700',
        fontSize: 16,
        color: theme.colors.primary,
        fontVariant: ['tabular-nums'],
    },
    purchaseSummaryValueMuted: {
        color: theme.colors.secondary,
    },
    purchaseTotalText: {
        fontWeight: '700',
        fontSize: 18,
        color: theme.colors.primary,
    },
    purchaseSummaryCard: {
        backgroundColor: theme.colors.grey0,
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 12,
        marginBottom: 12,
        borderWidth: 0,
    },
    purchaseSummaryCardInline: {
        marginTop: 8,
        marginBottom: 0,
    },
    purchaseSummaryDivider: {
        borderTopWidth: 1,
        borderColor: '#eee',
        marginTop: 6,
        paddingTop: 6,
    },
    purchaseDetailsSummaryDivider: {
        borderTopWidth: 1,
        borderColor: theme.colors.grey1,
        marginTop: 6,
        paddingTop: 8,
    },
    purchaseSummaryHeroRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    purchaseSummaryAvatar: {
        width: 46,
        height: 46,
        borderRadius: 23,
        backgroundColor: theme.colors.primary + '18',
        alignItems: 'center',
        justifyContent: 'center',
    },
    purchaseSummaryAvatarText: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.primary,
    },
    purchaseSummaryHeroText: {
        flexShrink: 1,
        gap: 2,
    },
    purchaseSummarySellerName: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.black,
    },
    purchaseSummaryDateText: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
    },
    purchaseSummaryStatsRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
        backgroundColor: theme.colors.grey0,
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 4,
        marginTop: 12,
    },
    purchaseSummaryStatCell: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 2,
        paddingHorizontal: 6,
    },
    purchaseSummaryStatValue: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 17,
        fontWeight: '700',
        color: theme.colors.black,
        textAlign: 'center',
        fontVariant: ['tabular-nums'],
    },
    purchaseSummaryStatLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 11,
        fontWeight: '600',
        color: theme.colors.grey4,
        textAlign: 'center',
        letterSpacing: 0.3,
        textTransform: 'uppercase',
    },
    purchaseSummaryStatLabelHighlight: {
        color: theme.colors.primary,
    },
    purchaseSummaryStatDivider: {
        width: 0.5,
        backgroundColor: theme.colors.grey1,
        marginVertical: 6,
    },
    purchaseDetailList: {
        paddingBottom: 8,
    },
    purchaseDetailItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 4,
        borderBottomWidth: 0.5,
        borderColor: theme.colors.grey1,
        gap: 12,
    },
    purchaseDetailItemTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    purchaseDetailItemQty: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.primary,
        fontVariant: ['tabular-nums'],
    },
    purchaseDetailItemTotal: {
        fontWeight: '700',
        fontSize: 15,
        color: theme.colors.primary,
        fontVariant: ['tabular-nums'],
    },
    formActions: {
        gap: 10,
        marginTop: 12,
    },
    formCard: {
        backgroundColor: theme.colors.surface ?? theme.colors.white,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 1,
        gap: 2,
    },
    exportButton: {
        paddingVertical: 10,
        minHeight: 44,
    },
    purchaseActionsRow: {
        marginBottom: 15,
    },
    recentPurchasesTitle: {
        fontWeight: '700',
        fontSize: 16,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        color: theme.colors.primary,
        marginTop: 4,
        marginBottom: 8,
    },
    recentPurchasesHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 2,
        marginBottom: 1,
    },
    recentPurchasesCount: {
        fontSize: 12,
        color: '#999',
    },
    recentPurchasesList: {
        flex: 1,
    },
    recentPurchasesEmpty: {
        flexGrow: 1,
        justifyContent: 'center',
    },
    purchaseHistoryScreen: {
        flexDirection: 'column',
        padding: 15,
        backgroundColor: theme.colors.background,
        height: '100%',
    },
    purchaseHistoryContainer: {
        paddingHorizontal: 12,
        paddingBlock: 15
    },
    purchaseHistoryItems: {
        marginBottom: 25,
    },
    purchaseItemRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 4,
        borderBottomWidth: 0.5,
        borderColor: theme.colors.grey1,
        gap: 12,
    },
    purchaseItemTitle: {
        fontWeight: '600',
        fontSize: 15,
        color: theme.colors.black,
    },
    purchaseItemSubtitle: {
        fontSize: 13,
        color: theme.colors.tertiary,
        marginTop: 2,
    },
    purchaseItemTotal: {
        fontWeight: '700',
        fontSize: 15,
        color: theme.colors.black,
    },
    purchaseItemActions: {
        alignItems: 'flex-end',
        gap: 2,
    },
    purchaseItemButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 0,
    },
    purchaseItemEditor: {
        borderWidth: 1,
        borderColor: theme.colors.grey1,
        borderRadius: 12,
        padding: 10,
        marginTop: 12,
        gap: 4,
    },
    purchaseItemEditorFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginTop: 4,
    },
    addItemButton: {
        paddingVertical: 8,
        minHeight: 40,
        paddingHorizontal: 14,
    },
    addItemButtonTitle: {
        fontSize: 13,
    },
    editPurchaseList: {
        flex: 1,
        marginTop: 4,
    },
    editPurchaseItemsContent: {
        gap: 12,
        paddingBottom: 16,
    },
    editPurchaseFooter: {
        gap: 10,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: theme.colors.grey1,
        backgroundColor: theme.colors.background,
    },
    editPurchaseFooterTotal: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 4,
    },
    priceItemCardScroll: {
        marginTop: 8,
        marginBottom: 4,
    },
    priceItemListHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 6,
    },
    priceItemListTitle: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.grey4,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    priceItemCount: {
        minWidth: 20,
        paddingHorizontal: 6,
        paddingVertical: 1,
        borderRadius: 9,
        backgroundColor: theme.colors.primary + '14',
        fontSize: 11,
        fontWeight: '700',
        color: theme.colors.primary,
        textAlign: 'center',
        overflow: 'hidden',
    },
    priceItemCardList: {
        paddingVertical: 4,
    },
    priceItemDotsRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
        marginTop: 8,
    },
    priceItemDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.colors.grey2,
        opacity: 0.45,
    },
    priceItemDotActive: {
        width: 16,
        backgroundColor: theme.colors.primary,
        opacity: 1,
    },
    priceItemCard: {
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: theme.colors.grey1,
        backgroundColor: theme.colors.surface ?? theme.colors.white,
        padding: 14,
        gap: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 1,
    },
    priceItemCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    priceItemCardHeaderText: {
        flexShrink: 1,
        gap: 3,
    },
    priceItemCardTitle: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 17,
        fontWeight: '700',
        color: theme.colors.black,
        textTransform: 'capitalize',
        letterSpacing: 0.3,
    },
    priceItemCardUnit: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 11,
        fontWeight: '600',
        color: theme.colors.grey4,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    priceItemCardPriceBlock: {
        flexDirection: 'row',
        alignItems: 'baseline',
        gap: 2,
        marginLeft: 'auto',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: theme.colors.grey0,
    },
    priceItemCardPrice: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.black,
        letterSpacing: 0.2,
        fontVariant: ['tabular-nums'],
    },
    priceItemCardCurrency: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 12,
        fontWeight: '700',
        color: theme.colors.primary,
    },
    priceItemCardCounter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: theme.colors.grey0,
        borderRadius: 26,
        padding: 5,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    priceItemCardCounterActive: {
        backgroundColor: theme.colors.white,
        borderColor: theme.colors.primary + '33',
    },
    priceItemCardStepperButton: {
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 0.5,
        borderColor: theme.colors.grey1,
        backgroundColor: theme.colors.white,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
        elevation: 1,
    },
    priceItemCardStepperButtonDisabled: {
        opacity: 0.35,
    },
    priceItemCardStepperButtonPlus: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    priceItemCardStepperButtonText: {
        fontSize: 24,
        fontWeight: '700',
        color: theme.colors.primary,
        lineHeight: 26,
    },
    priceItemCardStepperButtonTextPlus: {
        fontSize: 24,
        fontWeight: '700',
        color: theme.colors.white,
        lineHeight: 26,
    },
    priceItemCardValueBubble: {
        minWidth: 72,
        height: 52,
        borderRadius: 26,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
        backgroundColor: 'transparent',
    },
    priceItemCardValue: {
        fontSize: 32,
        fontWeight: '700',
        color: theme.colors.grey2,
        textAlign: 'center',
        fontVariant: ['tabular-nums'],
    },
    priceItemCardValueActive: {
        color: theme.colors.primary,
    },
    priceItemCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 10,
        borderTopWidth: 0.5,
        borderTopColor: theme.colors.grey1,
    },
    priceItemCardFooterCalc: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        fontWeight: '500',
        color: theme.colors.grey4,
        letterSpacing: 0.2,
        fontVariant: ['tabular-nums'],
    },
    priceItemCardFooterTotal: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.primary,
        letterSpacing: 0.2,
        fontVariant: ['tabular-nums'],
    },


    // ===== PRICE TREND =====
    priceTrendContainer: {
        marginBottom: 12,
        padding: 10,
        backgroundColor: theme.colors.grey0,
        borderRadius: 12,
        borderWidth: 0,
    },
    priceTrendTitle: {
        fontWeight: '600',
        marginBottom: 6,
        color: theme.colors.primary,
    },
    priceTrendBarsRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 4,
        height: 40,
    },
    priceTrendBar: {
        flex: 1,
        borderRadius: 2,
    },
    priceTrendScaleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    priceTrendScaleText: {
        fontSize: 11,
        color: theme.colors.tertiary,
    },
})
