import type { ThemeOptions } from '@rneui/themed'
import { StyleSheet } from 'react-native'
import { DIMENSIONS, TYPOGRAPHY } from '../constants'

export const sellerStyles = (theme: ThemeOptions) => StyleSheet.create({
    // ===== SELLERS =====
    sellerActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    sellerInfo: {
        flex: 1,
        paddingRight: 10,
    },
    sellerNameText: {
        fontWeight: '600',
        fontSize: 15,
        color: theme.colors.black,
    },
    sellerPhoneText: {
        fontSize: 13,
        color: theme.colors.tertiary,
        marginTop: 2,
    },
    sellerRowDotLegend: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginTop: 4,
    },
    sellerRowDotText: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.black,
        fontVariant: ['tabular-nums'],
    },
    rowIconButton: {
        backgroundColor: theme.colors.neutral,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: DIMENSIONS.BORDER_RADIUS_SMALL,
    },
    rowIconDeleteButton: {
        backgroundColor: theme.colors.error + '14',
        borderWidth: 1,
        borderColor: theme.colors.error + '22',
    },
    // Enhanced seller list delete — soft danger with subtle border, matches app cards
    sellerDeleteButton: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: theme.colors.error + '12',
        borderWidth: 1,
        borderColor: theme.colors.error + '18',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 0,
        paddingVertical: 0,
    },
    sellerDeleteButtonPressed: {
        backgroundColor: theme.colors.error + '20',
        borderColor: theme.colors.error + '30',
    },
    // Detail screen danger zone
    sellerDangerCard: {
        marginTop: 16,
        padding: 16,
        borderRadius: 14,
        backgroundColor: theme.colors.error + '08',
        borderWidth: 1,
        borderColor: theme.colors.error + '18',
        gap: 12,
    },
    sellerDangerTitle: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.error,
        letterSpacing: 0.2,
    },
    sellerDangerDescription: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
        lineHeight: 18,
    },
    sellerDangerButton: {
        backgroundColor: theme.colors.error,
        borderRadius: 10,
        paddingVertical: 13,
        paddingHorizontal: 16,
        minHeight: 46,
        borderWidth: 0,
    },
    sellerDangerButtonTitle: {
        color: 'white',
        fontWeight: '700',
        fontSize: 14,
        letterSpacing: 0.2,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
    },
    sellerDetailHeaderActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    sellerDetailDeleteIconButton: {
        width: 38,
        height: 38,
        borderRadius: 10,
        backgroundColor: theme.colors.error + '12',
        borderWidth: 1,
        borderColor: theme.colors.error + '18',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sellerEditLabel: {
        color: theme.colors.primary,
        fontWeight: '700',
        fontSize: 14,
        letterSpacing: 0.3,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
    },
    sellerRowContactRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 3,
    },
    sellerRowContactText: {
        fontSize: 13,
        color: theme.colors.tertiary,
    },
    sellerRowEditButton: {
        width: 36,
        height: 36,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: theme.colors.primary + '18',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    avatarText: {
        fontWeight: '700',
        fontSize: 16,
        color: theme.colors.primary,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
    },
    sellerDetailsBackRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginBottom: 8,
        marginLeft: -4,
    },
    sellerDetailsBackTitle: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.primary,
        letterSpacing: 0.2,
    },
    sellerProfileCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        marginBottom: 14,
        backgroundColor: theme.colors.surface ?? theme.colors.white,
        borderRadius: 14,
        borderWidth: 0.5,
        borderColor: theme.colors.grey1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 1,
    },
    sellerProfileAvatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: theme.colors.primary + '18',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    sellerProfileInitial: {
        fontWeight: '700',
        fontSize: 22,
        color: theme.colors.primary,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
    },
    sellerProfileMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 4,
    },
    sellerStatsRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
        backgroundColor: theme.colors.grey0,
        borderRadius: 14,
        paddingVertical: 12,
        paddingHorizontal: 8,
        marginBottom: 14,
    },
    sellerStatCell: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingHorizontal: 6,
    },
    sellerStatIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: theme.colors.white,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0.5,
        borderColor: theme.colors.grey1,
    },
    sellerStatValue: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.black,
        textAlign: 'center',
    },
    sellerStatLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 11,
        fontWeight: '600',
        color: theme.colors.grey4,
        textAlign: 'center',
        letterSpacing: 0.3,
        textTransform: 'uppercase',
    },
    sellerStatDivider: {
        width: 0.5,
        backgroundColor: theme.colors.grey1,
        marginVertical: 8,
    },
    sellerSectionSpacer: {
        marginTop: 4,
    },
    sellerScrollContent: {
        paddingBottom: 24,
    },
    sellerHistoryDivider: {
        height: 2,
        backgroundColor: theme.colors.grey2,
        marginTop: 24,
        marginBottom: 8,
    },
    recordPaymentButton: {
        shadowColor: 'transparent',
        elevation: 0,
        shadowOpacity: 0,
        marginBottom: 14,
    },
    sellerStatsSkeleton: {
        paddingVertical: 24,
        alignItems: 'center',
    },
    sellerProfileSkeletonText: {
        flex: 1,
        gap: 8,
    },
    sellerSkeletonSectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    sellerSkeletonSectionAction: {
        marginLeft: 'auto',
    },
    sellerHistoryEmptyContent: {
        flexGrow: 1,
    },

    // ===== RECORD PAYMENT =====
    settleFullBalance: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        gap: 4,
        marginTop: 10,
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 8,
        backgroundColor: theme.colors.primary + '12',
    },
    settleFullBalanceText: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.primary,
    },
    paymentSlip: {
        backgroundColor: theme.colors.surface ?? theme.colors.white,
        borderRadius: 14,
        borderWidth: 0,
        paddingVertical: 16,
        paddingHorizontal: 16,
    },
    paymentSlipEyebrow: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 10,
        fontWeight: '700',
        color: theme.colors.grey4,
        textTransform: 'uppercase',
        letterSpacing: 1,
        textAlign: 'center',
    },
    paymentSlipSeller: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.black,
        textAlign: 'center',
        marginTop: 2,
    },
    paymentSlipDate: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 11,
        color: theme.colors.grey4,
        textAlign: 'center',
        marginTop: 1,
    },
    paymentSlipDashes: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginVertical: 12,
    },
    paymentSlipDash: {
        flex: 1,
        height: 1,
        borderRadius: 1,
        backgroundColor: theme.colors.grey2,
    },
    paymentSlipAmountBlock: {
        alignItems: 'center',
        marginBottom: 2,
    },
    paymentSlipAmountLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 10,
        fontWeight: '600',
        color: theme.colors.grey4,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 2,
    },
    paymentSlipAmountRow: {
        flexDirection: 'row',
        alignItems: 'baseline',
        gap: 4,
    },
    paymentSlipAmount: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 28,
        fontWeight: '700',
        color: theme.colors.primary,
        fontVariant: ['tabular-nums'],
    },
    paymentSlipAmountCurrency: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.primary,
    },
    paymentSlipRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 5,
    },
    paymentSlipRowLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
    },
    paymentSlipRowValue: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.black,
        fontVariant: ['tabular-nums'],
    },
    paymentSlipRowValueStrong: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.primary,
        fontVariant: ['tabular-nums'],
    },
    paymentFormBody: {
        flex: 1,
    },
    paymentBalanceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 4,
        paddingHorizontal: 4,
        marginBottom: 16,
    },
    paymentBalanceLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.tertiary,
    },
    paymentBalanceValue: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.black,
        fontVariant: ['tabular-nums'],
    },
    paymentField: {
        marginBottom: 16,
    },
    paymentFieldLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.grey5,
        marginBottom: 8,
    },
    paymentInput: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 16,
        color: theme.colors.black,
        backgroundColor: theme.colors.grey0,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
    },
    paymentFormError: {
        color: theme.colors.error,
        fontSize: 12,
        marginTop: 4,
    },
    paymentMethodChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    paymentMethodChip: {
        paddingVertical: 9,
        paddingHorizontal: 14,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: theme.colors.grey2,
        backgroundColor: theme.colors.grey0,
    },
    paymentMethodChipActive: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    paymentMethodChipText: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.grey5,
    },
    paymentMethodChipTextActive: {
        color: theme.colors.white,
    },
    paymentPurchasesBlock: {
        marginTop: 4,
    },
    paymentPurchasesScroll: {
        maxHeight: 132,
    },
    paymentPurchasesLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 11,
        fontWeight: '600',
        color: theme.colors.grey4,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 6,
    },
    paymentPurchaseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 4,
    },
    paymentPurchaseDate: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
    },
    paymentPurchaseTotal: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.black,
        fontVariant: ['tabular-nums'],
    },
    paymentPurchaseEmpty: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
    },
})
