import type { ThemeOptions } from '@rneui/themed'
import { StyleSheet } from 'react-native'
import { TYPOGRAPHY } from '../constants'

export const settingsStyles = (theme: ThemeOptions) => StyleSheet.create({
    // ===== SETTINGS =====
    settingsCard: {
        backgroundColor: theme.colors.surface ?? theme.colors.white,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    settingsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    settingsLabel: {
        fontWeight: '600',
        fontSize: 15,
        color: theme.colors.black,
    },
    settingsPickerWrapper: {
        width: 150,
    },
    settingsFooterNote: {
        fontSize: 12,
        color: theme.colors.grey4,
        textAlign: 'center',
        marginTop: 8,
    },
    settingsScrollContent: {
        flexGrow: 1,
        paddingBottom: 24,
        gap: 12,
    },
    settingsSectionCard: {
        backgroundColor: theme.colors.surface ?? theme.colors.white,
        borderRadius: 14,
        padding: 16,
        gap: 12,
        borderWidth: 0.5,
        borderColor: theme.colors.grey1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 1,
    },
    settingsSectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    settingsSectionIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.colors.primary + '18',
        alignItems: 'center',
        justifyContent: 'center',
    },
    settingsSectionTextBlock: {
        flex: 1,
    },
    settingsSectionTitle: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.black,
    },
    settingsSectionDescription: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
        lineHeight: 18,
        marginTop: 2,
    },
    settingsThemeOptionsRow: {
        flexDirection: 'row',
        gap: 10,
    },
    settingsThemeOption: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        paddingHorizontal: 6,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.grey1,
        backgroundColor: theme.colors.grey0,
    },
    settingsThemeOptionSelected: {
        borderColor: theme.colors.primary,
        backgroundColor: theme.colors.primary + '12',
        borderWidth: 1.5,
    },
    settingsThemeOptionPressed: {
        opacity: 0.85,
    },
    settingsThemeOptionIconCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: theme.colors.white,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0.5,
        borderColor: theme.colors.grey1,
    },
    settingsThemeOptionIconCircleSelected: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    settingsThemeOptionLabel: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.black,
        textAlign: 'center',
    },
    settingsThemeOptionLabelSelected: {
        color: theme.colors.primary,
    },
    settingsThemeOptionHint: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 11,
        color: theme.colors.grey4,
        textAlign: 'center',
    },
    settingsPreviewRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: theme.colors.grey0,
        borderRadius: 12,
        padding: 12,
        borderWidth: 0.5,
        borderColor: theme.colors.grey1,
    },
    settingsPreviewDot: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    settingsPreviewTextBlock: {
        flex: 1,
        gap: 6,
    },
    settingsPreviewBar: {
        height: 10,
        borderRadius: 5,
        backgroundColor: theme.colors.grey2,
    },
    settingsPreviewBarWide: {
        width: '70%',
    },
    settingsPreviewBarNarrow: {
        width: '45%',
        opacity: 0.7,
    },
    settingsPreviewPill: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        backgroundColor: theme.colors.success + '18',
    },
    settingsAboutNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    settingsAppName: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.black,
        flex: 1,
    },
    settingsVersionPill: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: theme.colors.grey0,
        borderWidth: 0.5,
        borderColor: theme.colors.grey1,
    },
    settingsVersionText: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 11,
        fontWeight: '600',
        color: theme.colors.grey4,
    },
    settingsAppTagline: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
        lineHeight: 18,
    },
})
