import type { ThemeOptions } from '@rneui/themed'
import { StyleSheet } from 'react-native'
import { DIMENSIONS, TYPOGRAPHY } from '../constants'

export const sharedStyles = (theme: ThemeOptions) => StyleSheet.create({
    // ===== SHARED - BUTTONS =====
    raisedButtonContainer: {
        shadowColor: 'transparent',
        elevation: 0,
        shadowOpacity: 0,
    },
    raisedButtonContainerCompact: {
        alignSelf: 'flex-start',
        width: 'auto',
    },
    primaryButton: {
        backgroundColor: theme.colors.primary,
        borderRadius: 10,
        paddingVertical: 14,
        paddingHorizontal: 16,
        minHeight: 50,
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
        elevation: 2,
    },
    primaryButtonTitle: {
        color: theme.colors.white,
        fontWeight: '700',
        fontSize: 14,
        letterSpacing: 0.3,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
    },
    primaryButtonCompact: {
        backgroundColor: theme.colors.primary,
        borderRadius: 10,
        paddingVertical: 0,
        paddingHorizontal: 14,
        height: 40,
        minHeight: 40,
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
        elevation: 2,
    },
    primaryButtonTitleCompact: {
        color: theme.colors.white,
        fontWeight: '700',
        fontSize: 13,
        letterSpacing: 0.3,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
    },
    secondaryButton: {
        backgroundColor: theme.colors.white,
        borderRadius: 10,
        paddingVertical: 14,
        paddingHorizontal: 16,
        minHeight: 50,
        borderWidth: 1,
        borderColor: theme.colors.grey2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 1,
    },
    secondaryButtonTitle: {
        color: theme.colors.grey5,
        fontWeight: '600',
        fontSize: 14,
        letterSpacing: 0.2,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
    },
    iconButtonBase: {
        minWidth: 36,
        height: 36,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        paddingHorizontal: 8,
        paddingVertical: 0,
        elevation: 0,
        shadowOpacity: 0,
        borderWidth: 0,
    },
    iconButtonCompact: {
        minWidth: 36,
        width: 36,
        height: 36,
        paddingHorizontal: 0,
    },
    iconButtonSmall: {
        minWidth: 32,
        width: 32,
        height: 32,
        paddingHorizontal: 0,
    },
    iconButtonPrimary: {
        backgroundColor: theme.colors.primary,
    },
    iconButtonSecondary: {
        backgroundColor: theme.colors.grey0,
        borderWidth: 1,
        borderColor: theme.colors.grey1,
    },
    iconButtonGhost: {
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    iconButtonTitlePrimary: {
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 18,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        marginLeft: 8,
        color: 'white',
    },
    iconButtonTitleSecondary: {
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 18,
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        marginLeft: 8,
        color: theme.colors.primary,
    },

    // ===== SHARED - FORM FIELDS =====
    formErrorText: {
        color: theme.colors.error,
        fontSize: 12,
    },
    formInputLabel: {
        fontWeight: '600',
        color: theme.colors.primary,
    },
    formInputContainer: {
        borderBottomWidth: 0,
        borderRadius: DIMENSIONS.BORDER_RADIUS_SMALL,
        paddingBlock: 4,
        paddingHorizontal: 4,
        marginTop: 10,
        backgroundColor: theme.colors.secondary,
    },
    formInput: {
        paddingHorizontal: 12,
        fontSize: 18,
        paddingBlock: 8,
    },
    formCheckboxText: {
        fontWeight: '600',
        color: theme.colors.primary,
        fontSize: 16,
    },
    formCheckboxContainer: {
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: theme.colors.secondary,
        borderRadius: DIMENSIONS.BORDER_RADIUS_SMALL,
    },
    formButtonGroupButton: {
        borderWidth: 0,
        backgroundColor: theme.colors.secondary,
    },
    formButtonGroupSelectedButton: {
        backgroundColor: theme.colors.white,
        borderRadius: DIMENSIONS.BORDER_RADIUS_SMALL,
        borderWidth: 0.5,
        borderColor: theme.colors.secondary,
    },
    formButtonGroupSelectedText: {
        fontWeight: 'bold',
        color: theme.colors.black,
        fontSize: 14,
    },
    formButtonGroupButtonText: {
        fontWeight: '600',
        fontSize: 14,
        color: theme.colors.primary,
    },
    formButtonGroupInnerBorder: {
        color: theme.colors.secondary,
    },

    // ===== GLOBAL =====
    container: {
        flex: 1,
    },
    sectionHeaderContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
        gap: 12,
    },
    sectionHeaderContainerWithBack: {
        marginBottom: 10,
        gap: 6,
    },
    sectionHeaderBackButton: {
        marginLeft: -8,
        marginTop: -5,
    },
    sectionHeaderTitleWithBack: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 17,
        fontWeight: '700',
        color: theme.colors.primary,
        letterSpacing: 0.2,
        lineHeight: 22,
    },
    sectionHeaderDescriptionWithBack: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 12,
        fontWeight: '400',
        color: theme.colors.grey4,
        lineHeight: 16,
    },
    sectionHeaderTextBlock: {
        flex: 1,
        gap: 8,
    },
    sectionHeaderTitle: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 20,
        fontWeight: '700',
        color: theme.colors.primary,
        letterSpacing: 0.2,
        lineHeight: 26,
    },
    sectionHeaderTitleCompact: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.primary,
        letterSpacing: 0.2,
        lineHeight: 20,
    },
    sectionHeaderDescription: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        fontWeight: '400',
        color: theme.colors.grey4,
        lineHeight: 18,
        marginTop: 2,
    },
    sectionHeaderDescriptionContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: 12,
        marginTop: 4,
    },
    sectionHeaderContactRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    sectionHeaderContactText: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        fontWeight: '400',
        color: theme.colors.grey4,
        lineHeight: 18,
        flexShrink: 1,
    },
    emptyStateContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 32,
        paddingHorizontal: 24,
        gap: 10,
    },
    emptyStateIconCircle: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: theme.colors.grey0,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 4,
    },
    emptyStateContainerCompact: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        paddingHorizontal: 24,
        gap: 4,
    },
    emptyStateIconCircleCompact: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: theme.colors.grey0,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyStateTitle: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.grey5,
        textAlign: 'center',
    },
    emptyStateDescription: {
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 13,
        color: theme.colors.grey4,
        textAlign: 'center',
        lineHeight: 18,
    },
    fillContainer: {
        flex: 1,
    },
    sectionHeaderTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    detailSheetBody: {
        gap: 8,
        marginTop: 12,
    },
    // ===== UNDO TOAST =====
    undoToast: {
        width: '90%',
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 16,
        backgroundColor: '#2B2B2F',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
    },
    undoToastText: {
        flex: 1,
        color: '#F5F5F5',
        fontFamily: TYPOGRAPHY.FONT_FAMILY_SECONDARY,
        fontSize: 14,
    },
    undoToastAction: {
        color: '#F0C8E0',
        fontFamily: TYPOGRAPHY.FONT_FAMILY_PRIMARY,
        fontSize: 14,
        fontWeight: '700',
        letterSpacing: 0.5,
        textTransform: 'uppercase',
    },
    // ===== SKELETON =====
    cardSkeletonContainer: {
        padding: 16,
        backgroundColor: theme.colors.surface ?? theme.colors.white,
        borderRadius: 16,
        marginBottom: 12,
        gap: 10,
    },
    cardSkeletonRow: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 4,
    },
})
